/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_echo_EchoServerActivity */

#ifndef _Included_com_mtptwo_cppsupport_EchoServerActivity
#define _Included_com_mtptwo_cppsupport_EchoServerActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mtptwo_cppsupport_EchoServerActivity_TCP
#define com_mtptwo_cppsupport_EchoServerActivity_TCP 1L
#undef com_mtptwo_cppsupport_EchoServerActivity_UDP
#define com_mtptwo_cppsupport_EchoServerActivity_UDP 2L
/*
 * Class:     com_apress_echo_EchoServerActivity
 * Method:    nativeStartTcpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mtptwo_cppsupport_EchoServerActivity_nativeStartTcpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apress_echo_EchoServerActivity
 * Method:    nativeStartUdpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mtptwo_cppsupport_EchoServerActivity_nativeStartUdpServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
