/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_echo_EchoClientActivity */

#ifndef _Included_com_mtptwo_cppsupport_EchoClientActivity
#define _Included_com_mtptwo_cppsupport_EchoClientActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_echo_EchoClientActivity
 * Method:    nativeStartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mtptwo_cppsupport_EchoClientActivity_nativeStartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
